### ISSUE TITLE
[Bug]: Automatic events are not logged properly

### ISSUE THREAD

**Issue by YankoSoulisimo** [oddbit/flutter_facebook_app_events#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The automatic Purchase, StartTrial events are not logged properly - only a small part of the actual trials and purchases are logged as Facebook automatic events. This is observed for both iOS and Android versions of our app. We use the latest package version.  We have set up everything as per the instructions on the flutter part, as well as on the native part - info.plist and Android.manifest. The case is that there are a few events logged for the Purchase and StartTrial events for iOS, similar for Android - however, the Purchase event there is not logged at all. 
For iOS we enable the auto events logging after we get the app tracking permission. 

### Expected Behavior

Automatic events should be logged and should match actual trials and purchases.

### Steps To Reproduce

Install the flutter package.
Configure iOS and Android apps as per Facebook guidelines
Enable automatic event collection
Test the app
(Our apps are in production and are available on the Stores, so the problems exist both in debug and in release)

### Platform

Android, iOS

### Flutter Doctor

```shell
No issues
```

**Comment by antonoddbit** [comment]
We are investigating this issue first

**Comment by MlecznyU** [comment]
Same for me, we had call with facebook team, and pixel is configured properly.

**Comment by maxads74** [comment]
Same for me, But it has stopped working a day ago.

**Comment by maxads74** [comment]
Maybe can help. I think the problem is our.

I have added to my AppDelegate.swift file (This is the Facebook recommendation):

import AppTrackingTransparency
import FBAudienceNetwork

  if #available(iOS 14, *) {
      //print("eto es una kk")
      FBAdSettings.setAdvertiserTrackingEnabled(true)
                ATTrackingManager.requestTrackingAuthorization(completionHandler: { (status) in
                    switch status{
                    case .authorized:
                        FBAdSettings.setAdvertiserTrackingEnabled(true)

                        break
                    case .denied:
                        FBAdSettings.setAdvertiserTrackingEnabled(false)
             
                    default:
                        break
                    }
                })
            }


Maybe this previous one is not necessary if you do this (check transparency):

if (await AppTrackingTransparency.trackingAuthorizationStatus == TrackingStatus.authorized) {
    //print('ALF --> activo parametros por si las moscas');
    await facebookAppEvents.setAutoLogAppEventsEnabled(true);
    await facebookAppEvents.setAdvertiserTracking(enabled: true);
  }

**Comment by devibrahimkarahan** [comment]
Any updates on this guys? @maxads74 @antonoddbit @MlecznyU

**Comment by maxads74** [comment]
Hi Ibrahim

this is fixed. Thanks, sorry to not reply this emails.

Thanks a lot.

**Comment by devibrahimkarahan** [comment]
We are using Facebook SDK 16.2.1 but we cant see Start Trial and Purchase events, how did you resolve it? Did you fix it with setAdvertiserTracking method usage as you mentioned [here] ?(https://github.com/oddbit/flutter_facebook_app_events/issues/326#issuecomment-1859164839)

**Comment by MlecznyU** [comment]
> Any updates on this guys? @maxads74 @antonoddbit @MlecznyU

Hi, we still have the same problems. We will try this solution [comment](https://github.com/oddbit/flutter_facebook_app_events/issues/326#issuecomment-1859164839) and then we let you know

**Comment by YankoSoulisimo** [comment]
It looks like now there is an internal facebook sdk issue with StartTrial and Subscribe events:

https://github.com/facebook/facebook-ios-sdk/issues/2196

**Comment by hhzhangzy** [comment]
> 现在看来 StartTrial 和 Subscribe 事件存在内部 facebook sdk 问题：
> 
> [脸书/facebook-ios-sdk#2196](https://github.com/facebook/facebook-ios-sdk/issues/2196)

**Comment by hhzhangzy** [comment]
@maxads74 I integrated the 0.19.2 version of the SDK and configured the Android settings and XML files according to the documentation. However, I did not add any code to call the SDK. Can I still see the automatically collected Android application installation events on the Facebook platform? However, in reality, the collected events are not accurate and relatively few.

**Comment by devibrahimkarahan** [comment]
Did you find a solution @MlecznyU?
